# Generated by Django 6.0.3 on 2026-09-02 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_emailverification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailverification',
            old_name='password',
            new_name='password_hash',
        ),
    ]
