# Generated by Django 6.1.1 on 2026-09-15 09:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reports', '0003_match'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('unique_identification_details', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('claimant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='reports.report')),
            ],
        ),
        migrations.CreateModel(
            name='ClaimEvidence',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('evidence_url', models.FileField(max_length=500, upload_to='claim_evidence/')),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='claims.claim')),
            ],
        ),
        migrations.CreateModel(
            name='ClaimVerification',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('owner_id_verified', models.BooleanField(default=False)),
                ('item_visual_match', models.BooleanField(default=False)),
                ('location_proximity', models.BooleanField(default=False)),
                ('ownership_proof', models.BooleanField(default=False)),
                ('verification_status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('match_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('claim', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification', to='claims.claim')),
            ],
        ),
    ]
