# Generated by Django 6.1.1 on 2026-09-15 05:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_reportimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('match_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('found_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='found_matches', to='reports.report')),
                ('lost_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lost_matches', to='reports.report')),
            ],
        ),
    ]
